export const UPDATE_SEARCH_INPUT = 'UPDATE_SEARCH_INPUT';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const UPDATE_SEARCH_SUGGESTIONS = 'UPDATE_SEARCH_SUGGESTIONS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const SELECT_ADDRESS = 'SELECT_ADDRESS';
export const CLEAR_ADDRESS = 'CLEAR_ADDRESS';

export const UPDATE_RESULTS = 'UPDATE_RESULTS';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
